### ISSUE TITLE
How to reimplement the result of cora dataset?

### ISSUE THREAD

**Issue by liuyishoua** [FelixDJC/GRADATE#1]
l have change the alpha and beta as the paper reported for "cora" dataset, 0.9,0.3, respectively. And all the hyperparameter are used default in this repository. However, only 89.73 in AUC which make me confused.
![图片](https://user-images.githubusercontent.com/39064056/227901319-918c728c-c728-4a5d-a91b-04c8a4097230.png)

![图片](https://user-images.githubusercontent.com/39064056/227901718-d45ab7d6-3db1-4178-9fe5-95ec13457c4a.png)

**Comment by liuyishoua** [comment]
As CoLA and ANEMONE setting, l change all negative sample ratio to 1 for cora dataset. The AUC result does increase to 90.11, however still lower than the paper reported. Hope you respond, sincerely.

**Comment by FelixDJC** [comment]
![Snipaste_2023-03-29_08-01-06](https://user-images.githubusercontent.com/91123343/228393240-42d8de1b-bae5-4e1b-ba9b-7d7490522e72.png)

**Comment by liuyishoua** [comment]
Seed !
