### ISSUE TITLE
dgl version is too low

### ISSUE THREAD

**Issue by hmtbgc** [FelixDJC/GRADATE#3]
Hello, your work is excellent and I want to follow it. However, the dgl version is too low and I cannot install 0.4.x dgl. There are many strange errors when running on latest dgl 1.1.x. Can you update your code for latest version of dgl ? Thanks for advance!

**Comment by FelixDJC** [comment]
We need a sampling function in dgl=0.4.1 to sample subgraphs around nodes.
In the experiments, we found that the package does not contain this function when its version is larger than 0.4.1.
If you cannot install this package, you can reproduce the sampling function or find another package that can also achieve the function.
