### ISSUE TITLE
Question about Datasets 

### ISSUE THREAD

**Issue by ZhongLIFR** [FelixDJC/GRADATE#4]
Dear Authors,

Thank you for your nice paper and implementation. May I ask if it is possible to kindly provide other datasets in the form of .mat file? I know you have indicated a link to download original files (in a closed issue). However, it still requires some efforts to convert them into mat file and inject anomalies.

If you think these files are too large to upload onto Github, please consider upload them onto Zenodo and then provide a link. Looking forward to your reply and thank you in advance.

**Comment by FelixDJC** [comment]
I am unable to upload these datasets due to internet reasons. I suggest you download them from this link (https://github.com/yueliu1999/Awesome-Deep-Graph-Clustering).
