### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Djerry-h** [FelixDJC/GRADATE#5]
Is there a dataset that has been injected into the anomalous node?

**Comment by shihwang** [comment]
+1

**Comment by FelixDJC** [comment]
https://github.com/yueliu1999/Awesome-Deep-Graph-Clustering

**Comment by Djerry-h** [comment]
这些似乎都是用于图分类地数据集，我想问问您地代码中哪一部份是写异常点注入的？

**Comment by FelixDJC** [comment]
https://github.com/GRAND-Lab/CoLA
